name: Hockey Yukon
favicon: null
layout_spectrum: 0.667795650428161
typography_spectrum: 0.8048737216740847
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.6276538446545601
  lightness: 0.5162750910967588
  saturation: 0.7042190111242235
  rhythmicContrast: 0.8071352050174028
purpose: []
